### ISSUE TITLE
Feat(anta): Update runner to support AntaTestTemplate

### ISSUE THREAD

**Issue by titom73** [arista-netdevops-community/anta#212]
Possible approach:

```yaml
anta.tests.aaa:
  - VerifyAAAMethods:
      method: login
      template_params:
        - stage: authentication
        - stage: authorization
        - stage: accounting
```

This will require a change in the loader. 

```python
    res = await asyncio.gather(
        *(
            test[0](device=device,
                    template_params=test[1].get("template_params", [])
                    ).test(
                eos_data=None,
                **{k: v for k, v in test[1].items() if k != 'template_params'}
            )
            for device, test in itertools.product(inventory.get_inventory(established_only=established_only, tags=tags), tests)
        ),
        return_exceptions=True,
    )
```

idea provided by @carl-baillargeon
