### ISSUE TITLE
feat: TestResults should have test input parameters

### ISSUE THREAD

**Issue by gmuloc** [arista-netdevops-community/anta#269]
e.g.

if I run

```
anta.tests.connectivity:
  - VerifyReachability: 
     template_params:
       - src: 1.1.1.1
       - dst: 10.0.0.01
  - VerifyReachability: 
     template_params:
       - src: 1.1.1.1
       - dst: 10.0.0.02
```

Then there is no way to distinguish one test from another in the test results
