### ISSUE TITLE
Map tags to inventory devices and test catalog 

### ISSUE THREAD

**Issue by gusmb** [arista-netdevops-community/anta#44]
Increase flexibility by using tags on inventory devices and the test catalog, so that catalog tests can run on relevant devices only. For instance, in s typical EVPN scenario there.might be some tests that should run only in spines and some other tests only on leaf switches, having also some tests that run on all devices. Using tags or filters on tests and inventory devices could achieve this easily and add flexibility to the way tests execute. For inventory networks/ranges, tags would apply to the whole range/network...

**Comment by titom73** [comment]
We are going to start tag implementation with the following approach:

- Inventory file:

```yaml
anta_inventory:
  hosts:
  - host: 192.168.0.10
     tags: []
  - host: 192.168.0.11
     tags: []
  - host: 192.168.0.12
  - host: 192.168.0.13
  - host: 192.168.0.14
  - host: 192.168.0.15
  networks:
  - network: 192.168.110.0/24
  # ranges:
  # - start: 10.0.0.9
  #   end: 10.0.0.11
```
