### ISSUE TITLE
Doc: Add documentation for the device filter in the test catalog.

### ISSUE THREAD

**Issue by carl-baillargeon** [arista-netdevops-community/anta#442]
Add example and documentation on how to use the device filter in the test catalog.

https://www.anta.ninja/main/usage-inventory-catalog/#test-catalog

```yaml
---
anta.tests.aaa:
  - VerifyTacacsSourceIntf:
      intf: Loopback0
      vrf: default
      filters:
        tags:
          - AAA
        devices:
          - DC1-LEAF1A
 ```
