### ISSUE TITLE
`anta get from-cvp` does not build inventory with Management IP addresses

### ISSUE THREAD

**Issue by mtache** [arista-netdevops-community/anta#459]

**Comment by titom73** [comment]
Issue is not related to ANTA getting information but more about CVP/EOS setup:

- Cloudvision provision section is using 1 IP address as Management Address
- EOS configuration is using another IP Address on Management interface

![cvp-provisioning-s1-core1](https://github.com/arista-netdevops-community/anta/assets/4608573/89d4f279-cc4b-42e9-bc2a-81b6bd198fd4)

- API is exposing IP Address provisioned for management in CVP

![cvp-api-get-device-s1-core1](https://github.com/arista-netdevops-community/anta/assets/4608573/22088e2b-21d7-4933-a24b-f1136a0a887e)

Output of `anta get from-cvp` is created with correct IP address from CVP standpoint

```yaml
anta_inventory:
  hosts:
  - host: 192.168.0.243
    name: s1-core2
    tags:
    - s1-core
  - host: 192.168.0.224
    name: s1-core1
    tags:
    - s1-core

```
