### ISSUE TITLE
Investigate custom error messages when `ValidationError` occurs

### ISSUE THREAD

**Issue by mtache** [arista-netdevops-community/anta#463]

**Comment by gmuloc** [comment]
please add context :)

**Comment by mtache** [comment]
E.g of invalid test catalog:
```yaml
anta.tests.mlag:
  - VerifyMlagReloadDelay:
     reload_delay: 300
     reload_delay_non_mlag: 330
```
